### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by xsc27** [digitalr00ts/fizzbuzzx#47]
Pull request #46 introduced failing tests.

**Comment by pelmini** [comment]
Ill try to take a stab at this

**Comment by pelmini** [comment]
@xsc27 So, I took a look at the error that we were getting with the linting tests, and it seems to be an issue with the way we are calling the lint command? We get a `ERROR: InvocationError for command /bin/sh -c 'flakehell lint *.py' (exited with code 1)`. Not sure how to fix this though. From my understanding of the command, are we basically just piping the flakehell lint command to a shell command interpreter, so that way we can run the flakehell lint command to all the python files we have?
